### PR TITLE
interp: set EUID

### PR DESCRIPTION
**Pull request by anderbubble**
Set EUID variable analog to UID.

Signed-off-by: Jonathon Anderson <janderson@ciq.co>

### CODE REVIEW

**Comment by anderbubble** [comment]
This is meant to be a better fix for https://github.com/apptainer/apptainer/issues/837 than is possible downstream. (e.g., https://github.com/apptainer/apptainer/pull/937)

**Review by mvdan — CHANGES_REQUESTED** [review]
did you mean to use https://pkg.go.dev/os#Geteuid?

**Comment by anderbubble** [comment]
Absolutely. I was just too far down my downstream thought process, where we had been planning to set EUID=$UID in a script. Thanks for pointing this out.

PR updated.

**Review by mvdan — APPROVED** [review]
SGTM, thanks. Add a couple of tests mirroring the existing ones for UID? I think one `test` and one `unset` test should be enough.

**Comment by anderbubble** [comment]
@mvdan how about these?

**Review by mvdan — APPROVED** [review]

**Comment by anderbubble** [comment]
Thanks for the merge!

Do you have an estimate for when this might be included in a release?

**Comment by mvdan** [comment]
I'll probably do a bugfix release in the coming weeks. I just did a minor (feature) release, so that likely won't happen again for a few months. If you need this sooner, you should be able to use master.

**Comment by DrDaveD** [comment]
So, would you include this in a bugfix release?

**Comment by mvdan** [comment]
Sure, why not. It doesn't feel too risky. Though, again, you should be able to use master easily.

**Pull request merged**
