### PR TITLE
Fix home dir (~) expansion on Windows

### PR DESCRIPTION
**Pull request by andreynering**
This worked on Windows, but only on environments, like Git Bash, that sets the $HOME environment variable to improve compatibility with Unix tools.

While using Commnand Prompt or PowerShell, the real user path is available at $USERPROFILE or $HOMEDRIVE + $HOMEPATH.

See homedir implementation for reference:

https://github.com/mitchellh/go-homedir/blob/af06845cf3004701891bf4fdb884bfe4920b3727/homedir.go#L148

### CODE REVIEW

**Comment by mvdan** [comment]
All the CI environments are broken?

Also, please don't add an external dependency for this. Use https://golang.org/pkg/os/#UserHomeDir; master only supports 1.12 and up now.

**Comment by andreynering** [comment]
Interesting, all tests passes for me locally on macOS.

Perhaps it's a Linux specific issue?

**Comment by mvdan** [comment]
Mac is failing there too, so I doubt it.

**Comment by mvdan** [comment]
Also, I haven't updated CI to use 1.12 and up yet, but I'll do that today or tomorrow :)

**Comment by andreynering** [comment]
@mvdan homedir is a pretty small library that doesn't use C, unlike `os/user`. Anyway, updated to use the standard library.

**Comment by mvdan** [comment]
Note that I mentioned `os.UserHomeDir`, which has no cgo at all. It basically does the better version of what my code did here.

I suspect that the best mechanism would be to check $HOME first, and UserHomeDir as a fallback. This way, platforms like Windows would try both.

**Comment by mvdan** [comment]
I also wonder why `user.Lookup` didn't work for your scenario. Were you building a binary without CGo?

**Comment by andreynering** [comment]
> I also wonder why `user.Lookup` didn't work for your scenario. Were you building a binary without CGo?

Note that the real cause of this bug is the fact that the function returned if `name == ""`, even if `$HOME` was blank. The fallback code wasn't running in this scenario.

**Comment by andreynering** [comment]
And thanks, I didn't know `os.UserHomeDir` was a thing.

**Comment by mvdan** [comment]
Ah, sorry, I've been misreading this patch. The expand package isn't buggy per se. If anything, its call to `os/user` should be removed entirely. It's up to the caller to ensure that `$HOME` is set up properly.

And this is what the `interp` package does. In `Runner.Reset`, if `$HOME` isn't set, it uses `os/user.Current().HomeDir`. That's what should be swapped with `os.UserHomeDir`, which would make it work in cases where CGo is not enabled.

But again, this should all work on plain Windows, unless you were building with `CGO_ENABLED=0`. I'm all for making it work without CGo, though.

**Comment by mvdan** [comment]
(In the future, filing a bug might be the best way to discuss subtle bugs and fixes like these; otherwise, with a patch I have to guess what you're trying to fix and why)

**Comment by andreynering** [comment]
For some reason, this bug is happening even without `CGO_ENABLED=0`. There might be something else...

**Comment by mvdan** [comment]
We should be discussing all of this on an issue, with clear reproduction steps :) Then we could also write a regression test that actually ensures we fix the bug for good.

**Comment by andreynering** [comment]
Sorry, I was just trying to have a bug fixed here 🙂 

Opening an issue in a minute...

**Pull request closed without merging**
