### PR TITLE
interp: fix redirect path when Runner.Dir option is used

### PR DESCRIPTION
**Pull request by andreynering**

### CODE REVIEW

**Comment by mvdan** [comment]
Nice find - but please add a test :) I have others like this, just grep for `mkdir .* cd` in `interp_test.go`.

**Comment by andreynering** [comment]
Test case added.

**Comment by mvdan** [comment]
Oh no; what I meant is something like `mkdir -p a/b && cd a && cd b && cd ../..`, which tests it for `cd`. There is no need to add a full `Runner` test.

You could do something like: `mkdir a && cd a && echo foo >b && cd .. && cat a/b`

**Comment by andreynering** [comment]
Hmm... you're right. Updated. :smile:

**Comment by mvdan** [comment]
Thanks!

**Pull request merged**
