### PR TITLE
Preserve script parameters when invoking set.

### PR DESCRIPTION
**Pull request by bilus**
The code is far from pretty but I want to make a minimal change since you said you're working on it on v3. This is a blocker for us working on https://oya.sh

### CODE REVIEW

**Comment by mvdan** [comment]
Thanks for the PR. Is there an open or closed issue about this bug? It doesn't seem to me like the same issue I fixed in v3.

**Comment by mvdan** [comment]
Hmm, this is a bug in both v3 (now master) and v2. I think the underlying issue is in Params, so a nicer fix might be possible.

**Comment by mvdan** [comment]
I've found a nicer fix, which will work when using `Params` as an option directly too. I've also added more test cases. I'll backport into the v2 branch shortly; you can pull the latest commit from that without the need for me to tag `v2.6.5`.

**Comment by bilus** [comment]
Thanks, perfect!

**Comment by mvdan** [comment]
The backport is ee3cf905f3a4dd7a6fbfb5899f21304c64a92233.

**Pull request closed without merging**
